# Generated by Django 5.1.7 on 2025-04-13 18:56

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestiveCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Checking", "Checking"),
                            ("Savings", "Savings"),
                            ("Cash", "Cash"),
                            ("Credit Card", "Credit Card"),
                            ("Line of Credit", "Line of Credit"),
                            ("Emergency Fund", "Emergency Fund"),
                            ("Mortgage", "Mortgage"),
                            ("Loan", "Loan"),
                            ("Student Loan", "Student Loan"),
                            ("Personal Loan", "Personal Loan"),
                            ("Medical Debt", "Medical Debt"),
                            ("Other Debt", "Other Debt"),
                            ("Asset", "Asset"),
                            ("Liability", "Liability"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "available_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "lock_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("$", "US Dollar ($)"),
                            ("€", "Euro (€)"),
                            ("₹", "Indian rupee (₹)"),
                            ("£", "British Pound (£)"),
                            ("CAD", "Canadian Dollar ($)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "interest_rate",
                    models.FloatField(
                        default=0.0, verbose_name="Interest rate"),
                ),
                ("include_net_worth", models.BooleanField(default=True)),
                (
                    "liability_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Debt", "Debt"),
                            ("Loan", "Loan"),
                            ("Mortgage", "Mortgage"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "interest_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Per day", "Per day"),
                            ("Per month", "Per month"),
                            ("Per year", "Per year"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("mortgage_date", models.DateField(blank=True, null=True)),
                (
                    "mortgage_monthly_payment",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "mortgage_year",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "transaction_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "plaid_account_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("mask", models.CharField(blank=True, max_length=200, null=True)),
                ("subtype", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("ai_response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aichat_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("exception_type", models.CharField(
                    db_index=True, max_length=255)),
                ("error_message", models.TextField()),
                ("traceback", models.TextField()),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("count", models.PositiveIntegerField(default=1)),
                ("code", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("resolved", "Resolved"),
                            ("open", "Open"),
                            ("skip", "Skip"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="error_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Error Log",
                "verbose_name_plural": "Error Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AvailableFunds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_fund", models.CharField(max_length=20)),
                ("lock_fund", models.CharField(max_length=20)),
                ("created_at", models.DateField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_account",
                        to="my_finance.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("date", models.DateField()),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Yearly", "Yearly"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("auto_bill", models.BooleanField(default=False)),
                ("auto_pay", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_details_account",
                        to="my_finance.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("$", "US Dollar ($)"),
                            ("€", "Euro (€)"),
                            ("₹", "Indian rupee (₹)"),
                            ("£", "British Pound (£)"),
                            ("CAD", "Canadian Dollar ($)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        blank=True, default="unpaid", max_length=50, null=True
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Yearly", "Yearly"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("auto_bill", models.BooleanField(default=False)),
                ("auto_pay", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_account",
                        to="my_finance.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bill_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_details",
                        to="my_finance.billdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CapexBudgetDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roof", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "water_heater",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "all_appliances",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "bathroom_fixtures",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("drive_way", models.CharField(
                    blank=True, max_length=500, null=True)),
                ("furnance", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "air_conditioner",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("flooring", models.CharField(blank=True, max_length=500, null=True)),
                ("plumbing", models.CharField(blank=True, max_length=500, null=True)),
                ("electrical", models.CharField(
                    blank=True, max_length=500, null=True)),
                ("windows", models.CharField(blank=True, max_length=500, null=True)),
                ("paint", models.CharField(blank=True, max_length=500, null=True)),
                ("kitchen", models.CharField(blank=True, max_length=500, null=True)),
                ("structure", models.CharField(
                    blank=True, max_length=500, null=True)),
                ("components", models.CharField(
                    blank=True, max_length=500, null=True)),
                (
                    "landscaping",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "other_budgets",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "total_budget_cost",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capex_budget_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClosingCostDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_tax", models.CharField(max_length=30)),
                ("legal_fee", models.CharField(max_length=30)),
                ("title_insurance", models.CharField(max_length=30)),
                ("inspection", models.CharField(max_length=30)),
                ("appraisal_fee", models.CharField(max_length=30)),
                ("appliances", models.CharField(max_length=30)),
                ("renovation_cost", models.CharField(max_length=30)),
                ("others_cost", models.CharField(max_length=500)),
                (
                    "total_investment",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closing_cost_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("month", models.DateField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("$", "US Dollar ($)"),
                            ("€", "Euro (€)"),
                            ("₹", "Indian rupee (₹)"),
                            ("£", "British Pound (£)"),
                            ("CAD", "Canadian Dollar ($)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_finance.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpensesDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_tax", models.CharField(max_length=30)),
                ("insurance", models.CharField(max_length=30)),
                ("maintenance", models.CharField(max_length=30)),
                ("water", models.CharField(max_length=30)),
                ("gas", models.CharField(max_length=30)),
                ("electricity", models.CharField(max_length=30)),
                ("water_heater_rental", models.CharField(max_length=30)),
                ("other_utilities", models.CharField(max_length=500)),
                ("management_fee", models.CharField(max_length=30)),
                ("vacancy", models.CharField(max_length=30)),
                ("capital_expenditure", models.CharField(max_length=30)),
                ("other_expenses", models.CharField(max_length=500)),
                ("total_expenses", models.CharField(max_length=30)),
                ("inflation_assumption", models.CharField(max_length=30)),
                ("appreciation_assumption", models.CharField(max_length=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature", models.CharField(max_length=255)),
                ("issue", models.CharField(max_length=255)),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="feedback_screenshots/"
                    ),
                ),
                ("description", models.TextField()),
                ("suggestion", models.TextField()),
                ("importance", models.CharField(max_length=255)),
                ("is_reviewed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "income_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("income_date", models.DateField()),
                ("auto_income", models.BooleanField(default=False)),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Yearly", "Yearly"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("auto_credit", models.BooleanField(default=False)),
                ("primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_account",
                        to="my_finance.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncomeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "income_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("income_date", models.DateField(blank=True, null=True)),
                ("credited", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_detail_account",
                        to="my_finance.account",
                    ),
                ),
                (
                    "income",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_finance.income",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MortgageCalculator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=30)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("$", "US Dollar ($)"),
                            ("€", "Euro (€)"),
                            ("₹", "Indian rupee (₹)"),
                            ("£", "British Pound (£)"),
                            ("CAD", "Canadian Dollar ($)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                ("years", models.CharField(max_length=10)),
                ("interest", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortgagecalculator_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MortgageDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("interest_rate", models.CharField(max_length=30)),
                ("amortization_year", models.CharField(max_length=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortgage_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("notes", models.TextField()),
                ("added_on", models.DateField(default=datetime.date.today)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaidItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=255)),
                ("item_id", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="my_finance.plaiditem"
            ),
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "property_image",
                    models.ImageField(blank=True, null=True,
                                      upload_to="property_pics"),
                ),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Apartment", "Apartment"),
                            ("Commercial", "Commercial"),
                            ("Condo", "Condo"),
                            ("Duplex", "Duplex"),
                            ("House", "House"),
                            ("Mixed-Use", "Mixed-Use"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("post_code", models.CharField(
                    blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "unit_details",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("$", "US Dollar ($)"),
                            ("€", "Euro (€)"),
                            ("₹", "Indian rupee (₹)"),
                            ("£", "British Pound (£)"),
                            ("CAD", "Canadian Dollar ($)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                ("include_net_worth", models.BooleanField(default=False)),
                ("units_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "total_monthly_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "total_tenants",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payee_name", models.CharField(
                    blank=True, max_length=255, null=True)),
                ("expense_date", models.DateField(blank=True, null=True)),
                ("unit_name", models.CharField(
                    blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_info",
                        to="my_finance.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_expense_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unit_name", models.CharField(
                    blank=True, max_length=255, null=True)),
                ("item_type", models.CharField(
                    blank=True, max_length=255, null=True)),
                (
                    "item_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("quantity", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "item_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "already_paid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("invoice_due_date", models.DateField(blank=True, null=True)),
                ("invoice_paid_date", models.DateField(blank=True, null=True)),
                (
                    "invoice_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("record_payment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_details",
                        to="my_finance.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_invoice_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_name", models.CharField(
                    blank=True, max_length=255, null=True)),
                (
                    "tenant_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A/C", "A/C"),
                            ("Appliance ", "Appliance "),
                            ("Electrical", "Electrical"),
                            ("Heat", "Heat"),
                            ("Kitchen", "Kitchen"),
                            ("Plumbing", "Plumbing"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Unresolved", "Unresolved"),
                            ("Resolved", "Resolved"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_maintenance_details",
                        to="my_finance.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_maintenance_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyPurchaseDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("best_case_price", models.CharField(max_length=30)),
                ("likely_case_price", models.CharField(max_length=30)),
                ("worst_case_price", models.CharField(max_length=30)),
                ("selected_case", models.CharField(max_length=30)),
                (
                    "selected_price",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("down_payment", models.CharField(max_length=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_purchase_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyRentalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_name", models.CharField(
                    blank=True, max_length=255, null=True)),
                (
                    "rental_term",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rental_start_date", models.DateField(blank=True, null=True)),
                ("rental_end_date", models.DateField(blank=True, null=True)),
                (
                    "deposit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("deposit_due_date", models.DateField(blank=True, null=True)),
                (
                    "deposit_check",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rent_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "rent_due_every_month",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("rent_due_date", models.DateField(blank=True, null=True)),
                (
                    "rental_summary",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("first_name", models.CharField(
                    blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(
                    blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_address",
                        to="my_finance.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_rental_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Revenues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("month", models.DateField(blank=True, null=True)),
                ("end_month", models.DateField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("$", "US Dollar ($)"),
                            ("€", "Euro (€)"),
                            ("₹", "Indian rupee (₹)"),
                            ("£", "British Pound (£)"),
                            ("CAD", "Canadian Dollar ($)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("primary", models.BooleanField(default=False)),
                ("non_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RevenuesDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_1", models.CharField(max_length=30)),
                ("others_revenue_cost", models.CharField(max_length=500)),
                ("total_revenue", models.CharField(max_length=30)),
                ("rent_increase_assumption", models.CharField(max_length=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rev_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentalPropertyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_image",
                    models.ImageField(blank=True, null=True,
                                      upload_to="property_pics"),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("$", "US Dollar ($)"),
                            ("€", "Euro (€)"),
                            ("₹", "Indian rupee (₹)"),
                            ("£", "British Pound (£)"),
                            ("CAD", "Canadian Dollar ($)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "investor_details",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("include_net_worth", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capex_budget_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capex_budget",
                        to="my_finance.capexbudgetdetails",
                    ),
                ),
                (
                    "closing_cost_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closing_cost_user",
                        to="my_finance.closingcostdetails",
                    ),
                ),
                (
                    "monthly_expenses",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_user",
                        to="my_finance.expensesdetails",
                    ),
                ),
                (
                    "mortgage_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortgage_user",
                        to="my_finance.mortgagedetails",
                    ),
                ),
                (
                    "purchase_price_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_purchase_user",
                        to="my_finance.propertypurchasedetails",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_property_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "monthly_revenue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rev_user",
                        to="my_finance.revenuesdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockHoldings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                ("value", models.CharField(max_length=255)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stockholdings_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_finance.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="income",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_finance.subcategory",
            ),
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("$", "US Dollar ($)"),
                            ("€", "Euro (€)"),
                            ("₹", "Indian rupee (₹)"),
                            ("£", "British Pound (£)"),
                            ("CAD", "Canadian Dollar ($)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "initial_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "budget_spent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "budget_left",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("auto_budget", models.BooleanField(default=True)),
                ("auto_pay", models.BooleanField(default=True)),
                (
                    "budget_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Yearly", "Yearly"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("budget_status", models.BooleanField(default=False)),
                ("budget_start_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateField(blank=True, null=True)),
                ("ended_at", models.DateField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_account",
                        to="my_finance.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_finance.subcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("$", "US Dollar ($)"),
                            ("€", "Euro (€)"),
                            ("₹", "Indian rupee (₹)"),
                            ("£", "British Pound (£)"),
                            ("CAD", "Canadian Dollar ($)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "initial_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "budget_spent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "budget_left",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("auto_budget", models.BooleanField(default=True)),
                ("auto_pay", models.BooleanField(default=True)),
                (
                    "budget_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Yearly", "Yearly"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("budget_status", models.BooleanField(default=False)),
                ("budget_start_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateField(blank=True, null=True)),
                ("ended_at", models.DateField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_finance.subcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("transaction_date", models.DateField(blank=True, null=True)),
                (
                    "split_transactions",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("payee", models.CharField(max_length=25)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("in_flow", models.BooleanField(default=False)),
                ("out_flow", models.BooleanField(default=True)),
                (
                    "plaid_account_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "plaid_transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cleared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_finance.account",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_finance.bill",
                    ),
                ),
                (
                    "budgets",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_finance.budget",
                    ),
                ),
                (
                    "categories",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_finance.subcategory",
                    ),
                ),
                (
                    "tags",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_finance.tag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserBudgets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_date", models.DateField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("$", "US Dollar ($)"),
                            ("€", "Euro (€)"),
                            ("₹", "Indian rupee (₹)"),
                            ("£", "British Pound (£)"),
                            ("CAD", "Canadian Dollar ($)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("goal_amount", models.FloatField()),
                ("allocate_amount", models.FloatField()),
                ("fund_amount", models.FloatField(default=0)),
                ("budget_amount", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_finance.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_finance.subcategory",
                    ),
                ),
                (
                    "user_budget",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_finance.userbudgets",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="budget",
            name="user_budget",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_finance.userbudgets",
            ),
        ),
        migrations.AddField(
            model_name="billdetail",
            name="user_budget",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_finance.userbudgets",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="user_budget",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_finance.userbudgets",
            ),
        ),
    ]
