# Generated by Django 3.0.5 on 2021-06-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='auto_budget',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_period',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_spent',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
