# Generated by Django 5.1.7 on 2025-04-17 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="my_finance.plaiditem",
            ),
        ),
    ]
