# Generated by Django 3.0.5 on 2021-02-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
