# Generated by Django 3.0.5 on 2021-03-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0002_transaction_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='interestrate',
            field=models.FloatField(default=0.0, verbose_name='Interest rate'),
        ),
    ]
