# Generated by Django 5.1.7 on 2025-04-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0002_alter_account_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbudgets',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
