# Generated by Django 3.0.5 on 2021-06-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0002_auto_20210613_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=10, null=True),
        ),
    ]
