# Generated by Django 3.0.5 on 2023-04-26 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0002_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='name',
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_finance.SubCategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_finance.SubCategory'),
        ),
    ]
