# Generated by Django 3.0.5 on 2021-05-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0003_auto_20210502_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='interest_period',
            field=models.CharField(blank=True, choices=[('Per day', 'Per day'), ('Per month', 'Per month'), ('Per year', 'Per year')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='liability_type',
            field=models.CharField(blank=True, choices=[('Debt', 'Debt'), ('Loan', 'Loan'), ('Mortgage', 'Mortgage')], max_length=10, null=True),
        ),
    ]
