# Generated by Django 3.0.5 on 2021-06-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0003_auto_20210622_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='remaining_amount',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
