# Generated by Django 5.1.7 on 2025-04-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_finance", "0003_userbudgets_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbudgets",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
