# Generated by Django 3.0.5 on 2023-04-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0003_auto_20230426_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
