# Generated by Django 3.0.5 on 2021-06-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0004_bill_remaining_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
