# Generated by Django 3.0.5 on 2023-04-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0004_transaction_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
