# Generated by Django 3.0.5 on 2021-05-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0004_auto_20210502_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remaining_amount',
            field=models.CharField(default=2000, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TransactionSummary',
        ),
    ]
