# Generated by Django 3.0.5 on 2021-05-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0005_auto_20210503_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
