# Generated by Django 3.0.5 on 2023-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0005_auto_20230426_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Checking', 'Checking'), ('Savings', 'Savings'), ('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Line of Credit', 'Line of Credit'), ('Mortgage', 'Mortgage'), ('Loan', 'Loan'), ('Student Loan', 'Student Loan'), ('Personal Loan', 'Personal Loan'), ('Medical Debt', 'Medical Debt'), ('Other Debt', 'Other Debt'), ('Asset', 'Asset'), ('Liability', 'Liability')], max_length=50, null=True),
        ),
    ]
