# Generated by Django 3.0.5 on 2021-05-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0006_goal_goal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(blank=True, default='unpaid', max_length=50, null=True),
        ),
    ]
