# Generated by Django 3.0.5 on 2021-07-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0006_expenses_revenues'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='revenues',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='revenues',
            name='non_primary',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='revenues',
            name='primary',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
