# Generated by Django 3.0.5 on 2023-05-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0006_auto_20230508_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mortgage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='mortgage_monthly_payment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
