# Generated by Django 3.0.5 on 2021-07-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0007_auto_20210703_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenues',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
