# Generated by Django 3.0.5 on 2021-05-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0007_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mortgagecalculator',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)')], max_length=10, null=True),
        ),
    ]
