# Generated by Django 3.0.5 on 2023-05-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0007_auto_20230509_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_finance.SubCategory'),
        ),
    ]
