# Generated by Django 3.0.5 on 2023-05-18 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0008_auto_20230510_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_account', to='my_finance.Account'),
        ),
        migrations.AddField(
            model_name='bill',
            name='auto_bill',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='auto_pay',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_account', to='my_finance.Account'),
        ),
        migrations.AddField(
            model_name='budget',
            name='auto_pay',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
