# Generated by Django 3.0.5 on 2021-07-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0008_auto_20210703_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenues',
            name='end_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
