# Generated by Django 3.0.5 on 2021-05-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0009_auto_20210506_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='lock_amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
