# Generated by Django 3.0.5 on 2021-07-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0010_auto_20210715_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablefunds',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
