# Generated by Django 3.0.5 on 2021-07-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0011_auto_20210716_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablefunds',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
