# Generated by Django 3.0.5 on 2023-05-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0011_income_incomedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomedetail',
            name='income_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
