# Generated by Django 3.0.5 on 2023-05-29 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0012_incomedetail_income_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatebudget',
            name='auto_pay',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='templatebudget',
            name='budget_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatebudget',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_finance.SubCategory'),
        ),
        migrations.AlterField(
            model_name='templatebudget',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
