# Generated by Django 3.0.5 on 2021-07-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0012_auto_20210717_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='lock_amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
