# Generated by Django 3.0.5 on 2021-07-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0013_auto_20210717_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='currentbalance',
            new_name='allocate_amount',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='goalamount',
            new_name='goal_amount',
        ),
        migrations.AddField(
            model_name='goal',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_finance.Account'),
            preserve_default=False,
        ),
    ]
