# Generated by Django 3.0.5 on 2021-08-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0014_auto_20210717_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='over_spent',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_spent',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
