# Generated by Django 3.0.5 on 2023-06-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0015_stockholdings'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholdings',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
