# Generated by Django 3.0.5 on 2021-08-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0015_auto_20210807_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='over_spent',
        ),
    ]
