# Generated by Django 3.0.5 on 2021-08-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0016_remove_budget_over_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
