# Generated by Django 3.0.5 on 2023-07-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0017_auto_20230720_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='original_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='split_transactions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
