# Generated by Django 3.0.5 on 2021-08-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0017_auto_20210809_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='budget',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
