# Generated by Django 2.2.9 on 2024-06-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0018_auto_20230721_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='budget_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='fund_amount',
            field=models.FloatField(default=0),
        ),
    ]
