# Generated by Django 2.2.9 on 2024-07-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0019_auto_20240617_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Checking', 'Checking'), ('Savings', 'Savings'), ('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Line of Credit', 'Line of Credit'), ('Emergency Fund', 'Emergency Fund'), ('Mortgage', 'Mortgage'), ('Loan', 'Loan'), ('Student Loan', 'Student Loan'), ('Personal Loan', 'Personal Loan'), ('Medical Debt', 'Medical Debt'), ('Other Debt', 'Other Debt'), ('Asset', 'Asset'), ('Liability', 'Liability')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)'), ('CAD', 'Canadian Dollar ($)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)'), ('CAD', 'Canadian Dollar ($)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)'), ('CAD', 'Canadian Dollar ($)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)'), ('CAD', 'Canadian Dollar ($)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)'), ('CAD', 'Canadian Dollar ($)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mortgagecalculator',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)'), ('CAD', 'Canadian Dollar ($)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)'), ('CAD', 'Canadian Dollar ($)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rentalpropertymodel',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)'), ('CAD', 'Canadian Dollar ($)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='revenues',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)'), ('CAD', 'Canadian Dollar ($)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='templatebudget',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)'), ('CAD', 'Canadian Dollar ($)')], max_length=10, null=True),
        ),
    ]
