# Generated by Django 3.0.5 on 2021-08-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0019_auto_20210814_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_left',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
