# Generated by Django 3.0.5 on 2021-08-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0020_budget_budget_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='initial_amount',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
