# Generated by Django 3.0.5 on 2021-08-29 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_finance', '0021_auto_20210821_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('currency', models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)')], max_length=10, null=True)),
                ('initial_amount', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.CharField(blank=True, default=0, max_length=15, null=True)),
                ('budget_spent', models.CharField(blank=True, default=0, max_length=15, null=True)),
                ('budget_left', models.CharField(blank=True, default=0, max_length=15, null=True)),
                ('auto_budget', models.BooleanField(blank=True, default=True, null=True)),
                ('budget_period', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=10, null=True)),
                ('budget_status', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
