# Generated by Django 2.2.9 on 2024-07-15 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0022_populate_user_budgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='user_budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_finance.UserBudgets'),
        ),
        migrations.AddField(
            model_name='budget',
            name='user_budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_finance.UserBudgets'),
        ),
    ]
