# Generated by Django 3.0.5 on 2021-09-02 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_finance', '0022_templatebudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingCostDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_tax', models.CharField(max_length=30)),
                ('legal_fee', models.CharField(max_length=30)),
                ('title_insurance', models.CharField(max_length=30)),
                ('inspection', models.CharField(max_length=30)),
                ('appraisal_fee', models.CharField(max_length=30)),
                ('appliances', models.CharField(max_length=30)),
                ('renovation_cost', models.CharField(max_length=30)),
                ('others_cost', models.CharField(max_length=10000000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_cost_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_tax', models.CharField(max_length=30)),
                ('insurance', models.CharField(max_length=30)),
                ('maintenance', models.CharField(max_length=30)),
                ('water', models.CharField(max_length=30)),
                ('gas', models.CharField(max_length=30)),
                ('electricity', models.CharField(max_length=30)),
                ('water_heater_rental', models.CharField(max_length=30)),
                ('other_utilities', models.CharField(max_length=1000000000)),
                ('management_fee', models.CharField(max_length=30)),
                ('vacancy', models.CharField(max_length=30)),
                ('capital_expenditure', models.CharField(max_length=30)),
                ('other_expenses', models.CharField(max_length=1000000000)),
                ('total_expenses', models.CharField(max_length=30)),
                ('inflation_assumption', models.CharField(max_length=30)),
                ('appreciation_assumption', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MortgageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('interest_rate', models.CharField(max_length=30)),
                ('amortization_year', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPurchaseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_case_price', models.CharField(max_length=30)),
                ('likely_case_price', models.CharField(max_length=30)),
                ('worst_case_price', models.CharField(max_length=30)),
                ('selected_case', models.CharField(max_length=30)),
                ('down_payment', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_purchase_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevenuesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_1', models.CharField(max_length=30)),
                ('unit_2', models.CharField(max_length=30)),
                ('others_cost', models.CharField(max_length=1000000000)),
                ('total_revenue', models.CharField(max_length=30)),
                ('rent_increase_assumption', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalPropertyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('currency', models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)')], max_length=10, null=True)),
                ('include_net_worth', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closing_cost_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_closing_cost', to='my_finance.ClosingCostDetails')),
                ('monthly_expenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_expenses', to='my_finance.ExpensesDetails')),
                ('monthly_revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_revenue', to='my_finance.RevenuesDetails')),
                ('mortgage_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_mortgage', to='my_finance.MortgageDetails')),
                ('purchase_price_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_purchase', to='my_finance.PropertyPurchaseDetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_rental', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
