# Generated by Django 3.0.5 on 2021-09-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0023_closingcostdetails_expensesdetails_mortgagedetails_propertypurchasedetails_rentalpropertymodel_reven'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypurchasedetails',
            name='selected_price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
