# Generated by Django 2.2.9 on 2024-07-15 07:28

from django.db import migrations

def set_user_budget(apps, schema_editor):
    Budget = apps.get_model('my_finance', 'Budget')
    Bill = apps.get_model('my_finance', 'Bill')
    UserBudgets = apps.get_model('my_finance', 'UserBudgets')

    for budget in Budget.objects.all():
        user_budget = UserBudgets.objects.filter(user=budget.user).first()
        budget.user_budget = user_budget
        budget.save()
    for bill in Bill.objects.all():
        user_budget = UserBudgets.objects.filter(user=bill.user).first()
        bill.user_budget = user_budget
        bill.save()

def unset_user_budget(apps, schema_editor):
    Budget = apps.get_model('my_finance', 'Budget')
    Bill = apps.get_model('my_finance', 'Bill')

    for budget in Budget.objects.all():
        budget.user_budget = None
        budget.save()

    for bill in Bill.objects.all():
        bill.user_budget = None
        bill.save()

class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0023_auto_20240715_1257'),
    ]

    operations = [
        migrations.RunPython(set_user_budget,unset_user_budget),
    ]
