# Generated by Django 3.0.5 on 2021-09-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0024_propertypurchasedetails_selected_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenuesdetails',
            old_name='others_cost',
            new_name='others_revenue_cost',
        ),
        migrations.RemoveField(
            model_name='revenuesdetails',
            name='unit_2',
        ),
    ]
