# Generated by Django 2.2.9 on 2024-07-25 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_finance", "0024_auto_20240715_1258"),
    ]

    operations = [
        migrations.AddField(
            model_name="billdetail",
            name="user_budget",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_finance.UserBudgets",
            ),
        ),
    ]
