# Generated by Django 2.2.28 on 2024-08-14 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0025_billdetail_user_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='user_budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_finance.UserBudgets'),
        ),
    ]
