# Generated by Django 3.0.5 on 2021-09-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0025_auto_20210904_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='closingcostdetails',
            name='total_investment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rentalpropertymodel',
            name='closing_cost_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_cost_user', to='my_finance.ClosingCostDetails'),
        ),
        migrations.AlterField(
            model_name='rentalpropertymodel',
            name='monthly_expenses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_user', to='my_finance.ExpensesDetails'),
        ),
        migrations.AlterField(
            model_name='rentalpropertymodel',
            name='monthly_revenue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_user', to='my_finance.RevenuesDetails'),
        ),
        migrations.AlterField(
            model_name='rentalpropertymodel',
            name='mortgage_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_user', to='my_finance.MortgageDetails'),
        ),
        migrations.AlterField(
            model_name='rentalpropertymodel',
            name='purchase_price_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_purchase_user', to='my_finance.PropertyPurchaseDetails'),
        ),
    ]
