# Generated by Django 3.0.5 on 2021-09-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0027_auto_20210906_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpropertymodel',
            name='investor_details',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='InvestorDetails',
        ),
    ]
