# Generated by Django 3.0.5 on 2024-11-27 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_finance', '0027_aichat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aichat',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255)),
                ('issue', models.CharField(max_length=255)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='feedback_screenshots/')),
                ('description', models.TextField()),
                ('suggestion', models.TextField()),
                ('importance', models.CharField(max_length=255)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
