# Generated by Django 3.0.5 on 2024-12-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0028_errorlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorlog',
            old_name='error_description',
            new_name='user_suggestion',
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='error_page',
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='is_reviewed',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='page_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='referrer',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='error_screenshots/'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='error_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
