# Generated by Django 3.0.5 on 2021-09-07 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_finance', '0029_auto_20210906_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapexBudgetDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roof', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('water_heater', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('all_appliances', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('bathroom_fixtures', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('drive_way', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('furnance', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('air_conditioner', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('flooring', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('plumbing', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('electrical', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('windows', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('paint', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('kitchen', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('structure', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('components', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('landscaping', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('other_budgets', models.CharField(blank=True, max_length=10000000000000000, null=True)),
                ('total_budget_cost', models.CharField(blank=True, max_length=30, null=True)),
                ('rental_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_property', to='my_finance.RentalPropertyModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capex_budget_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
