# Generated by Django 3.0.5 on 2024-12-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0029_auto_20241210_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='page_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='referrer',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
