# Generated by Django 3.0.5 on 2021-09-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0030_capexbudgetdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capexbudgetdetails',
            name='rental_property',
        ),
        migrations.AddField(
            model_name='rentalpropertymodel',
            name='capex_budget_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='capex_budget', to='my_finance.CapexBudgetDetails'),
            preserve_default=False,
        ),
    ]
