# Generated by Django 3.0.5 on 2024-12-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0030_auto_20241211_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorlog',
            old_name='user_suggestion',
            new_name='error_description',
        ),
    ]
