# Generated by Django 3.0.5 on 2024-12-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0031_auto_20241211_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='error_code',
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='error_description',
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='page_url',
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='time',
        ),
    ]
