# Generated by Django 3.0.5 on 2021-10-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0031_auto_20210907_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mortgage_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
