# Generated by Django 3.0.5 on 2024-12-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0032_auto_20241212_1112'),
    ]

    operations = [
    ]
