# Generated by Django 3.0.5 on 2021-12-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0032_account_mortgage_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpropertymodel',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_pics'),
        ),
    ]
