# Generated by Django 3.0.5 on 2022-04-26 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_finance', '0033_rentalpropertymodel_property_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='value',
        ),
        migrations.AddField(
            model_name='property',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address_line12',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='post_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_pics'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Commercial', 'Commercial'), ('Condo', 'Condo'), ('Duplex', 'Duplex'), ('House', 'House'), ('Mixed-Use', 'Mixed-Use'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_details',
            field=models.CharField(blank=True, max_length=1000000000000, null=True),
        ),
        migrations.CreateModel(
            name='PropertyTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('property_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_prop_name', to='my_finance.Property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyRentalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rental_term', models.CharField(blank=True, max_length=255, null=True)),
                ('rental_start_date', models.DateField(blank=True, null=True)),
                ('rental_end_date', models.DateField(blank=True, null=True)),
                ('deposit_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('deposit_due_date', models.DateField(blank=True, null=True)),
                ('rent_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('rent_due_every_month', models.CharField(blank=True, max_length=255, null=True)),
                ('rent_due_date', models.DateField(blank=True, null=True)),
                ('rental_summary', models.CharField(blank=True, max_length=100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, null=True)),
                ('property_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_address', to='my_finance.Property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_rental_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
