# Generated by Django 3.0.5 on 2024-12-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0034_apperrorlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apperrorlog',
            old_name='status_code',
            new_name='code',
        ),
        migrations.AddField(
            model_name='apperrorlog',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('open', 'Open'), ('skip', 'Skip')], db_index=True, default='open', max_length=10),
        ),
        migrations.DeleteModel(
            name='ErrorLog',
        ),
    ]
