# Generated by Django 3.0.5 on 2022-04-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0034_auto_20220426_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='address_line12',
            new_name='address_line2',
        ),
        migrations.RenameField(
            model_name='propertytenant',
            old_name='property_address',
            new_name='property_detail',
        ),
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('₹', 'Indian rupee (₹)'), ('£', 'British Pound (£)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertyrentalinfo',
            name='deposit_check',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='include_net_worth',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
