# Generated by Django 3.0.5 on 2022-04-27 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0035_auto_20220427_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyrentalinfo',
            name='property_address',
        ),
        migrations.RemoveField(
            model_name='propertytenant',
            name='property_detail',
        ),
        migrations.AddField(
            model_name='property',
            name='rental_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_rental_info', to='my_finance.PropertyRentalInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='tenant_info',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='property_tenant_info', to='my_finance.PropertyTenant'),
            preserve_default=False,
        ),
    ]
