# Generated by Django 3.0.5 on 2022-04-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0036_auto_20220427_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='units_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
