# Generated by Django 3.0.5 on 2022-04-28 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0037_property_units_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rental_info',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tenant_info',
        ),
        migrations.AddField(
            model_name='propertyrentalinfo',
            name='property_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_address', to='my_finance.Property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertytenant',
            name='property_detail',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_prop_name', to='my_finance.Property'),
            preserve_default=False,
        ),
    ]
