# Generated by Django 3.0.5 on 2022-04-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0038_auto_20220428_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='total_monthly_rent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_tenants',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
