# Generated by Django 3.0.5 on 2022-04-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0040_auto_20220430_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrentalinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyrentalinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
