# Generated by Django 3.0.5 on 2022-04-30 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_finance', '0041_auto_20220430_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_type', models.CharField(blank=True, max_length=255, null=True)),
                ('item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('item_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('already_paid', models.CharField(blank=True, max_length=255, null=True)),
                ('balance_due', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_due_date', models.DateField(blank=True, null=True)),
                ('invoice_paid_date', models.DateField(blank=True, null=True)),
                ('invoice_status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('property_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_details', to='my_finance.Property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_invoice_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
