# Generated by Django 3.0.5 on 2022-05-07 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_finance', '0042_propertyinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('A/C', 'A/C'), ('Appliance ', 'Appliance '), ('Electrical', 'Electrical'), ('Heat', 'Heat'), ('Kitchen', 'Kitchen'), ('Plumbing', 'Plumbing'), ('Other', 'Other')], max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('property_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_maintenance_details', to='my_finance.Property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_maintenance_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
