# Generated by Django 3.0.5 on 2022-05-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0043_propertymaintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymaintenance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='propertymaintenance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
