# Generated by Django 3.0.5 on 2022-05-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0044_auto_20220507_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymaintenance',
            name='status',
            field=models.CharField(blank=True, choices=[('Unresolved', 'Unresolved'), ('Resolved ', 'Resolved ')], max_length=10, null=True),
        ),
    ]
