# Generated by Django 3.0.5 on 2022-05-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0045_auto_20220508_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymaintenance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
