# Generated by Django 3.0.5 on 2022-05-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0046_auto_20220508_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinvoice',
            name='record_payment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymaintenance',
            name='status',
            field=models.CharField(blank=True, choices=[('Unresolved', 'Unresolved'), ('Resolved', 'Resolved')], max_length=10, null=True),
        ),
    ]
