# Generated by Django 3.0.5 on 2022-08-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0050_plaiditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaiditem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plaiditem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='account',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_finance.PlaidItem'),
            preserve_default=False,
        ),
    ]
