# Generated by Django 3.0.5 on 2022-08-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0051_auto_20220823_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='plaid_account_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
