# Generated by Django 3.0.5 on 2022-08-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0052_auto_20220823_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='plaid_account_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
