# Generated by Django 3.0.5 on 2022-08-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finance', '0053_auto_20220823_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='plaid_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='plaid_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
