version = 1

test_patterns = ["test.py"]

exclude_patterns = [
  "migrations/**",
  "locale/**",
  "packages/**",
  "static/**/*.min.js",
  "static/app-assets/**",
  "static/assets/css/**",
  "static/assets/animations/**",
  "static/assets/scss/**",
  "static/assets/js/app-calendars-events.js",
  "static/assets/js/app-calendars.js",
  "static/Images/**",
  "templates/**",
  "media/**",
  "**/test.py"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["jquery"]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"