# Category Icons
category_icons = {
        "Rent/Mortgage": "app-assets/images/categories/Rent.png",
        "Electricity": 'app-assets/images/categories/Electricity.png',
        "Water": "app-assets/images/categories/Water-Bill.png",
        "Internet": "app-assets/images/categories/Internet.png",
        "New Car": "app-assets/images/categories/Car.png",
        "Insurance": "app-assets/images/categories/Insurance.png",
        "Cellphone": "app-assets/images/categories/Phone.png",
        "Netflix Subscription": "app-assets/images/categories/Netflix.png",
        "Amazon Prime Subscription": "app-assets/images/categories/Amazon.png",
        "Gym Membership": "app-assets/images/categories/Gym.png",
        "Groceries": "app-assets/images/categories/Shoping.png",
        "Eating Out": "app-assets/images/categories/dinner.png",
        "Gas / Transportation": "app-assets/images/categories/transport.png",
        "Entertainment": "app-assets/images/categories/entertainment.png",
        "Pets": "app-assets/images/categories/pet.png",
        "Kids/Children": "app-assets/images/categories/children.png",
        "Taxes": "app-assets/images/categories/taxes.png",
        "Car Maintenance": "app-assets/images/categories/car-maintenance.png",
        "Medical Expenses": "app-assets/images/categories/medical.png",
        "Gifts": "app-assets/images/categories/gift-box.png",
        "Holidays": "app-assets/images/categories/holiday.png",
        "Emergency Fund": "app-assets/images/categories/emergency-fund.png",
        "Phone": "app-assets/images/categories/Phone.png",
        "New House": "app-assets/images/categories/Rent.png",
        "New Phone": "app-assets/images/categories/new-phone.png",
        "Education": "app-assets/images/categories/college-fee.png",
        "Netflix Spotify Subscription": "app-assets/images/categories/Netflix.png",
        "Amazon Prime Spotify Subscription" : "app-assets/images/categories/Amazon.png",
        "Hair": "app-assets/images/categories/salon.png",
        "Job": "app-assets/images/categories/job.png",
        "Business": "app-assets/images/categories/business.png",
        "Vacation": "app-assets/images/categories/vacation.png",
        "Electronic Items": "app-assets/images/categories/electronics.png",
        "Electronics": "app-assets/images/categories/electronics.png",
        "Public Transportation": "app-assets/images/categories/transport.png",
        "Retirement": "app-assets/images/categories/retirement.png",
        "Spotify Subscription": "app-assets/images/categories/spotify.png",
        "Bonus": "app-assets/images/categories/bonus.png",
        "Beauty": "app-assets/images/categories/beauty.png",
        "Clothes": "app-assets/images/categories/clothes-hanger.png",
        "Movies": "app-assets/images/categories/entertainment.png",
        "Interest": "app-assets/images/categories/interest-rate.png"
         
    }
