# version: "3.9"
services:
  dashboard:
    build: .
    command: python manage.py runserver 0.0.0.0:8072 --insecure
    ports:
      - "8072:8072"
    env_file:
      - .env
    environment:
      - DEBUG=1
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DB_NAME=personal_finance
      - SQL_USER=test
      - SQL_PASSWORD=test
      - SQL_HOST=postgres
      - SQL_PORT=5432
    volumes:
      - .:/finance # Mounts the current directory to the container's /finance directory
      - ./static:/finance/static # Mounts static files directory
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: finance_postgres
    restart: always
    environment:
      POSTGRES_DB: personal_finance
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d personal_finance"]
      interval: 10s
      retries: 5
      timeout: 5s

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com #
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
