# version: '3.7'

# services:
#   dashboard:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8072 --insecure
#     ports:
#       - "8072:8072"
#     env_file:
#       - ./.env
#     environment:
#       - DEBUG=1
#       - NOSQL_ENGINE=djongo
#       - NOSQL_NAME=personal_finance
#       - NOSQL_HOST=mongodb
#       - NOSQL_ENFORCE_SCHEMA=False
#     volumes:
#       - .:/finance  # Mounts the current directory to the container's /finance directory
#       - ./static:/finance/static  # Mounts static files directory
#     depends_on:
#       - mongodb
#     restart: unless-stopped

#   mongodb:
#     image: mongo
#     ports:
#       - 27019:27019
#     restart: unless-stopped

# volumes:
#   postgres_data:

# version: '3.7'

services:
  dashboard:
    build: .
    command: python manage.py runserver 0.0.0.0:8072 --insecure
    ports:
      - "8072:8072"
    env_file:
      - ./.env
    environment:
      - DEBUG=1
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DB_NAME=personal_finance
      - SQL_USER=your_user
      - SQL_PASSWORD=your_password
      - SQL_HOST=postgres
      - SQL_PORT=5432
    volumes:
      - .:/finance  # Mounts the current directory to the container's /finance directory
      - ./static:/finance/static  # Mounts static files directory
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: finance_postgres
    restart: always
    environment:
      POSTGRES_DB: personal_finance
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
